-- Generated by Mocodo 4.2.8

CREATE TABLE Belongs_to (
  PRIMARY KEY (category_id, place_id),
  category_id VARCHAR(42) NOT NULL,
  place_id    VARCHAR(42) NOT NULL
);

CREATE TABLE Category (
  PRIMARY KEY (category_id),
  category_id VARCHAR(42) NOT NULL,
  name        VARCHAR(42)
);

CREATE TABLE Comment (
  PRIMARY KEY (comment_id),
  comment_id VARCHAR(42) NOT NULL,
  rate       VARCHAR(42),
  content    VARCHAR(42),
  place_id   VARCHAR(42) NOT NULL,
  email      VARCHAR(42) NOT NULL
);

CREATE TABLE Place (
  PRIMARY KEY (place_id),
  place_id VARCHAR(42) NOT NULL,
  name     VARCHAR(42),
  street   VARCHAR(42),
  zip      VARCHAR(42),
  city     VARCHAR(42),
  country  VARCHAR(42),
  lat      VARCHAR(42),
  long     VARCHAR(42),
  image    VARCHAR(42),
  email    VARCHAR(42) NOT NULL
);

CREATE TABLE Saves (
  PRIMARY KEY (email, place_id),
  email    VARCHAR(42) NOT NULL,
  place_id VARCHAR(42) NOT NULL
);

CREATE TABLE User (
  PRIMARY KEY (email),
  email    VARCHAR(42) NOT NULL,
  nickname VARCHAR(42),
  password VARCHAR(42)
);

ALTER TABLE Belongs_to ADD FOREIGN KEY (place_id) REFERENCES Place (place_id);
ALTER TABLE Belongs_to ADD FOREIGN KEY (category_id) REFERENCES Category (category_id);

ALTER TABLE Comment ADD FOREIGN KEY (email) REFERENCES User (email);
ALTER TABLE Comment ADD FOREIGN KEY (place_id) REFERENCES Place (place_id);

ALTER TABLE Place ADD FOREIGN KEY (email) REFERENCES User (email);

ALTER TABLE Saves ADD FOREIGN KEY (place_id) REFERENCES Place (place_id);
ALTER TABLE Saves ADD FOREIGN KEY (email) REFERENCES User (email);
